### ISSUE TITLE
Update templates for MediaPackage dual-ingest

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-samples/aws-media-services-simple-live-workflow#13]
MediaPackage supports dual ingest URLs to match dual pipelines coming from MediaLive. We need to update template to:

Create one MediaPackage channel
Connect each MediaLive pipeline to each ingest URL from MediaPackage

**Comment by morjoan** [comment]
Both CloudFormation templates and manual instructions have been updated to accommodate this.
