### ISSUE TITLE
BufferSegments change in MediaLive

### ISSUE THREAD

**Issue by JimTharioAmazon** [aws-samples/aws-media-services-simple-live-workflow#15]
default value for BufferSegments to 5 in the console (HLS input attachments) so now when the customer loops the input they only get the last 5  segments in the manifest

**Comment by JimTharioAmazon** [comment]
It looks like the CloudFormation template works as expected. The UI default change for BufferSegments affects the manual instructions only.

**Comment by morjoan** [comment]
Updated instructions including screen captures.

**Comment by JimTharioAmazon** [comment]
Thank you!
