### ISSUE TITLE
CFN : Could not connect to the endpoint URL: \"https://api.mediatailor.eu-west-3.amazonaws.com/playbackConfiguration\

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/aws-media-services-simple-live-workflow#21]
Deployment of this cloudformation template `Entire Workshop`:   https://s3-us-west-2.amazonaws.com/rodeolabz-us-west-2/cloudformation/LiveStreamingWorkshopResources.json

Region : eu-west-3

Error Cloudformation 
```
| MediaTailorConfigResource | CREATE_FAILED | Failed to create resource. See the details in CloudWatch Log Stream: 2020/06/30/[$LATEST]0db51831fbf846238c8c15009f5f6c2a
```

Full logs from the Cloudwatch log group : /aws/lambda/LiveToVodWorkshop-MediaTailorModul-EMTConfigLambda-xxx

```json
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2020/06/30/[$LATEST]0db51831fbf846238c8c15009f5f6c2a",
    "PhysicalResourceId": "LiveToVodWorkshop-MediaTailorModuleStack-3NVPPYKBN9Z2-MediaTailorConfigResource",
    "StackId": "arn:aws:cloudformation:eu-west-3:xxx:stack/LiveToVodWorkshop-MediaTailorModuleStack-xxx/xx-bab8-11ea-8b98-0e1f48a18a9e",
    "RequestId": "xx-e628-483c-9667-xx",
    "LogicalResourceId": "MediaTailorConfigResource",
    "Data": {
        "Exception": "Could not connect to the endpoint URL: \"https://api.mediatailor.eu-west-3.amazonaws.com/playbackConfiguration\""
    }
}
```

**Comment by morjoan** [comment]
Hi there,
I think this failure is due to the fact the MediaTailor service is currently not available in eu-west-3. List of current supported regions are here: https://docs.amazonaws.cn/en_us/general/latest/gr/mediatailor.html

I will update the documentation to note this.
