### ISSUE TITLE
"Entire Workshop" Does Not build MediaTailor

### ISSUE THREAD

**Issue by smp** [aws-samples/aws-media-services-simple-live-workflow#5]
Ahoy! Deployed the 'entire workshop' template today, but it did not launch anything MediaTailor related as the documentation implies. Two solutions:

- update doc to specify that lab 5 is not included
- update template to include mediatailor

**Comment by morjoan** [comment]
Updated documentation to reflect that CloudFormation doesn't cover MediaTailor. Will update templates later on once MediaTailor has available SDK to make this happen.
